// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI90G78sFUY_9LHDjtpE2nOvurdFBUCZ0',
    appId: '1:992493733905:web:e061b8e64264c585e4c9b0',
    messagingSenderId: '992493733905',
    projectId: 'ite-apice-f2fca',
    authDomain: 'ite-apice-f2fca.firebaseapp.com',
    storageBucket: 'ite-apice-f2fca.firebasestorage.app',
    measurementId: 'G-061G20SQ2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Y5KbEeQkU5kYAcj-vcYxWTAOcMKztHs',
    appId: '1:992493733905:android:20dcd8420c0feffee4c9b0',
    messagingSenderId: '992493733905',
    projectId: 'ite-apice-f2fca',
    storageBucket: 'ite-apice-f2fca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUJFUvDyguBHaDje1rkIFLM02aqPJhmTc',
    appId: '1:992493733905:ios:de548afa15e179fbe4c9b0',
    messagingSenderId: '992493733905',
    projectId: 'ite-apice-f2fca',
    storageBucket: 'ite-apice-f2fca.firebasestorage.app',
    iosBundleId: 'com.example.iteApice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUJFUvDyguBHaDje1rkIFLM02aqPJhmTc',
    appId: '1:992493733905:ios:de548afa15e179fbe4c9b0',
    messagingSenderId: '992493733905',
    projectId: 'ite-apice-f2fca',
    storageBucket: 'ite-apice-f2fca.firebasestorage.app',
    iosBundleId: 'com.example.iteApice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI90G78sFUY_9LHDjtpE2nOvurdFBUCZ0',
    appId: '1:992493733905:web:648f25344b2c5655e4c9b0',
    messagingSenderId: '992493733905',
    projectId: 'ite-apice-f2fca',
    authDomain: 'ite-apice-f2fca.firebaseapp.com',
    storageBucket: 'ite-apice-f2fca.firebasestorage.app',
    measurementId: 'G-F8ED00VFD4',
  );
}
